apiVersion: v1
kind: Service
metadata:
  name: imposter-service
  labels:
    app: imposter-mock
  namespace: default
spec:
  selector:
    app: imposter-mock
  ports:
    - name: tcp-imposter-mock
      port: 80
      protocol: TCP
      targetPort: 8080
  type: ClusterIP